# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/RAM_Line/RAM_Line.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_Line || ORIG_REF_NAME==RAM_Line} -quiet] -quiet

# IP: ip/AXIS_Data_RAM/AXIS_Data_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXIS_Data_RAM || ORIG_REF_NAME==AXIS_Data_RAM} -quiet] -quiet

# IP: ip/clk_wiz_1/clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# IP: ip/rgb2dvi_0/rgb2dvi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
