# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/vivadofile/lab_102/lab_102.cache/wt [current_project]
set_property parent.project_path E:/vivadofile/lab_102/lab_102.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/vivadofile/IP_libarary1/IP_Core
  e:/vivadofile/IP_libarary1/FPGA-IP
} [current_project]
update_ip_catalog
set_property ip_output_repo e:/vivadofile/lab_102/lab_102.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/1_images/0_R.coe
add_files E:/1_images/0_B.coe
add_files E:/vivadofile/lab_102/images/0.coe
add_files E:/vivadofile/lab_102/images/1.coe
add_files E:/vivadofile/lab_102/images/2.coe
add_files E:/vivadofile/lab_102/images/3.coe
add_files E:/vivadofile/lab_102/images/4.coe
add_files E:/vivadofile/lab_102/images/5.coe
add_files E:/vivadofile/lab_102/images/6.coe
add_files E:/vivadofile/lab_102/images/7.coe
add_files E:/vivadofile/lab_102/images/8.coe
add_files E:/vivadofile/lab_102/images/9.coe
read_verilog -library xil_defaultlib {
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/Driver_Bayer_To_RGB.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/Driver_Csi_To_Dvp.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/Driver_IIC.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/Driver_MIPI.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/Image_Process_Edge.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/OV5647_Init.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/Trigger_Generator.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/digital_recognition.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/edge_track.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/image_processing.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/videoshow.v
  E:/vivadofile/lab_102/lab_102.srcs/sources_1/new/test.v
}
read_ip -quiet E:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/RAM_Line/RAM_Line.xci
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/RAM_Line/RAM_Line_ooc.xdc]

read_ip -quiet E:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/AXIS_Data_RAM/AXIS_Data_RAM.xci
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/AXIS_Data_RAM/AXIS_Data_RAM_ooc.xdc]

read_ip -quiet E:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet E:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet E:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/csi2_d_phy_rx_0/csi2_d_phy_rx_0.xci
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/csi2_d_phy_rx_0/hdl/csi2_d_phy_rx.xdc]

read_ip -quiet E:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/csi_to_axis_0/csi_to_axis_0.xci
set_property used_in_implementation false [get_files -all e:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/csi_to_axis_0/hdl/csi_to_axis.xdc]

read_ip -quiet E:/vivadofile/lab_102/lab_102.srcs/sources_1/ip/RGB_To_Gray_0/RGB_To_Gray_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivadofile/lab_102/lab_102.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files E:/vivadofile/lab_102/lab_102.srcs/constrs_1/new/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top test -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file test_utilization_synth.rpt -pb test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
